### ISSUE TITLE
MdIcon is missing

### ISSUE THREAD

**Issue by incognitojam** [SgLy/material-web-solid-js-typing#1]
I believe this is because `material-web/docs/components/icon.md` doesn't include any API docs:

```
<!-- auto-generated API docs start -->
<!-- auto-generated API docs end -->
```

**Comment by SgLy** [comment]
Although my script is directly finding a `Properties` table instead of this comment tag, I think it is actually the same reason (both these comment tags and the properties table are missing).

I made a quick dirty fix to add `md-icon`, it should be ok now.
